# Paths work on both Windows and Linux (forward slashes recommended)
sources:
  root: "./"

categories: ["M", "L", "r"]

destinations:
  - id: game_bmp
    path: "processed"
    #path: "../dev/BG1StylePortraits/BG1StylePortraits/portraits/"
    format: bmp
    mappings:
      M: { width: 210, height: 330 }
      L: { width: 420, height: 660 }
      r: { width: 420, height: 660 }

  - id: web_preview
    path: "promotion"
    #path: "../dev/BG1StylePortraits/docs/portraits/"
    format: webp
    webp_quality: 85
    mappings:
      M: { width: 420, height: 660 }
      L: { width: 420, height: 660 }
      r: { width: 420, height: 660 }
    thumbnails:
      max_size: 165
