# Paths work on both Windows and Linux (forward slashes recommended)
sources:
  root: "./"

categories: ["M", "L", "r"]

destinations:
  - id: game_bmp
    path: "processed/game_bmp"
    #path: "../dev/BG1StylePortraits/BG1StylePortraits/portraits/"
    format: bmp
    mappings:
      M: { width: 210, height: 330 }
      L: { width: 420, height: 660 }
      r: { width: 420, height: 660 }

  - id: web_preview
    path: "processed/promotion"
    #path: "../dev/BG1StylePortraits/docs/portraits/"
    format: webp
    webp_quality: 85
    mappings:
      M: { width: 420, height: 660 }
      L: { width: 420, height: 660 }
      r: { width: 420, height: 660 }
    thumbnails:
      max_size: 165
    contact_sheet:
      width: 1200
      thumb_width: 800
      cols: 9
      path: "processed/contact_sheets"

  - id: promo_compilation
    path: "processed/compilation"
    format: webp
    webp_quality: 85
    mappings:
      L: { width: 420, height: 660 }
    prefixes:
      bdimoen: z_sod_
      bdivicon: z_sod_
      caelar: z_sod_
      glint: z_sod_
      mkhiin: z_sod_
      schael: z_sod_
      voghiln: z_sod_